name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    uses: mrkkrp/haskell-ci/.github/workflows/haskell-ci.yml@master
    with:
      additional-packages: 'megaparsec-tests'
      ghc-versions: '["9.6.7", "9.8.4", "9.10.3", "9.12.4", "9.14.1"]'
