name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    uses: mrkkrp/haskell-ci/.github/workflows/haskell-ci.yml@master
    with:
      additional-packages: 'megaparsec-tests'
